# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a6cfc43cfe830fbef644e74eddafb20997d4b6b973b1fd067b0b04ca35c64f7edd8671e74f9632bbbed1cf951e3bff402910e168e3901f2c6f900de0991c39

test:
  secret_key_base: 47e7eee47fc71908b56f68fa0f8a455928c22134b6ae02f88b726d80fc59631a57cc272d259b76532dffd81e6639066beeea623b4c568745cf3eb68046775c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
